# -*- coding: utf-8 -*-
"""ProjectVendingMachine2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hs7WWnftC0NmzIT21SiwlXzVSmi_x8D5
"""

products = {
    1:{"name": "Water","price": 7},
    2:{"name": "Soda", "price": 15},
    3:{"name": "Green Tea", "price": 20},
    4:{"name": "Coffee", "price": 25},
    5:{"name": "Juice", "price": 30}
}

accepted_money = [1,5,10,20,50,100]
current_balance = 0

def show_products():
  print("\nProducts List")
  for code, item in products.items():
    print(f"{code}. {item['name']} - {item['price']} THB")
def insert_money():
  global current_balance
  while True:
    money = int(input("Insert money(1,5,10,20,50,100)or 0 to stop"))
    if money == 0:
      break
    elif money in accepted_money:
      current_balance += money
      print(f"current balance: {current_balance} THB")
    else:
      print ("Invalid Money")
def select_product():
  global current_balance
  choice = int(input("Select product"))
  if choice not in products:
    print("Invalid Choice")
    return

  product = products[choice]
  price = product["price"]
  if current_balance >= price:
    current_balance -= price
    print(f"\n Dispensing: {product['name']}")
    print(f"Change returned: {current_balance} THB")
    current_balance = 0
  else:
    print("Insufficient balance")
def vending_machine():
  print("Welcome to the Vending Machine!")
  show_products()
  insert_money()
  select_product()
  print("Thank you for using our Vending Machine!")
vending_machine()